server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
  # 模板引擎不缓存
  thymeleaf:
    cache: false

  # 文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: chenxp106
    url: jdbc:mysql://123.207.60.196:3306/myblog?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai


mybatis-plus:
  type-aliases-package: cn.gdut.system.entity
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cn.gdut.system.mapper: DEBUG
